node {
    stage('Build') {
        node {
            docker.image('python:3-alpine').inside {
                sh 'python -m py_compile add2vals.py calc.py'
            }
        }
    }
    
    stage('Test') {
        node {
            docker.image('qnib/pytest').inside {
                sh 'py.test --verbose --junit-xml test-reports/results.xml test_calc.py'
            }
        }
        
        try {
            junit 'test-reports/results.xml'
        } catch (Exception e) {
            // Handle any error or failure during test execution
        }
    }
}
